"""Plugin scaffolding.

    orchestrate plugin new rag --detect "eval/questions.jsonl"

Generates a working plugin AND the negative control for it, in one step,
because a plugin shipped without a negative control is a plugin nobody can
trust. The generated audit deliberately FAILS out of the box on the fixture it
also generates: your first run should be red, and making it green is the
exercise.

Three things the template enforces by construction, all of them mistakes this
project has already made and recorded:

  detect on SHAPE, never on a repo name       (works for any season/fork)
  never raise -- a crash is reported          (a crashed audit is not a pass)
  never pass silently when it cannot run      (skipped is UNKNOWN, not OK)
"""

from __future__ import annotations

import re
from pathlib import Path

PLUGIN = '''"""{title} plugin.

Everything {name}-specific lives here. The core does not import it and knows
nothing about it beyond the plugin list.
"""

from __future__ import annotations

from orchestrate_kit.evaluator.plugin_api import (
    AuditResult, Confidence, Finding, RepoContext, Severity, SimpleAudit,
)


def audit_example(ctx: RepoContext) -> AuditResult:
    """Replace this with a real check.

    Contract:
      * return an AuditResult; never raise (the runner reports a crash as a
        finding, but handling it here is better)
      * set `res.skipped` with a REASON when the check cannot run -- a skipped
        audit is an UNKNOWN, and the reporter says so. Returning `passed=True`
        because you could not look is how green checks become decorative.
      * every Finding needs literal evidence: command output or a file excerpt.
        A Finding without evidence is an opinion.
    """
    res = AuditResult("{name}-example", "{category}", True)

    target = ctx.read("{detect}")
    if not target:
        res.skipped = "{detect} not readable"
        return res

    # ---- replace from here -------------------------------------------
    # This deliberately fails against the generated fixture. Your first
    # `orchestrate selftest`-style run should be RED. An audit that has never
    # produced a finding has never been tested.
    res.passed = False
    res.findings.append(Finding(
        title="{name}: example audit is still a placeholder",
        severity=Severity.MEDIUM,
        confidence=Confidence.OBSERVED,
        evidence=f"{detect} exists ({{len(target)}} bytes) but nothing is checked",
        detail="Delete this finding once the audit does real work.",
        remediation="Implement the check, then add an injection to "
                    "tests/test_{name}_plugin.py proving it can fail.",
    ))
    # ---- to here ------------------------------------------------------
    return res


class {cls}Plugin:
    name = "{name}"
    description = "{title}"

    def audits(self):
        return [SimpleAudit("{name}-example", "{category}", audit_example)]

    def detect(self, ctx: RepoContext) -> bool:
        """Detect on SHAPE, never on a repository name.

        A name check works exactly once -- for your repo, this season. A shape
        check works for every fork, rename and future edition.
        """
        return ctx.exists("{detect}")
'''

TEST = '''"""Negative control for the {name} plugin.

Generated by `orchestrate plugin new`. These tests are not optional decoration:
a plugin whose audits have never produced a finding is a plugin nobody can
trust to produce one when it matters.
"""

from __future__ import annotations

import pytest

from orchestrate_kit.evaluator.plugin_api import RepoContext, Severity

from {module} import {cls}Plugin, audit_example


@pytest.fixture
def healthy(tmp_path):
    """The minimal repository this plugin considers correct."""
    target = tmp_path / "{detect}"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("replace with a realistic healthy fixture\\n",
                      encoding="utf-8")
    return RepoContext(root=tmp_path)


def test_detects_on_shape(healthy, tmp_path):
    assert {cls}Plugin().detect(healthy)


def test_does_not_detect_an_unrelated_repo(tmp_path):
    empty = RepoContext(root=tmp_path / "empty")
    (tmp_path / "empty").mkdir()
    assert not {cls}Plugin().detect(empty)


def test_skips_rather_than_passing_when_it_cannot_run(tmp_path):
    """The single most important test here. An audit that returns passed=True
    because it could not look is worse than no audit."""
    (tmp_path / "bare").mkdir()
    res = audit_example(RepoContext(root=tmp_path / "bare"))
    assert res.skipped, "must report WHY it could not run"


def test_audit_never_raises(tmp_path):
    """Feed it garbage. A crash must not escape."""
    junk = tmp_path / "junk"
    (junk / "{parent}").mkdir(parents=True, exist_ok=True)
    (junk / "{detect}").write_bytes(b"\\x00\\xff not valid text at all")
    audit_example(RepoContext(root=junk))   # must not raise


@pytest.mark.xfail(reason="placeholder audit; delete this marker once implemented")
def test_healthy_repo_is_clean(healthy):
    assert audit_example(healthy).passed


def test_the_audit_can_actually_fail(healthy):
    """THE negative control. Break the thing on purpose and require a finding.

    Replace the corruption below with a real defect once the audit is real. If
    this test ever needs weakening to pass, the audit is what changed."""
    (healthy.root / "{detect}").write_text("", encoding="utf-8")
    res = audit_example(healthy)
    assert res.skipped or res.findings, \\
        "the audit reported clean on deliberately broken input"


def test_every_finding_carries_evidence(healthy):
    for f in audit_example(healthy).findings:
        assert f.evidence.strip(), f"{{f.title}} has no evidence"
        assert f.severity in Severity
'''

README = """# `{name}` plugin

{title}

## Register it

```python
from {module} import {cls}Plugin

evaluator.register({cls}Plugin())
```

## Detection

Keys on `{detect}`. **Shape, not name** — so it applies to any fork or future
edition of the same problem, and never to a repo that merely shares a title.

## Before you open a PR

- [ ] `test_the_audit_can_actually_fail` passes with a REAL injected defect,
      not the placeholder
- [ ] the `xfail` marker on `test_healthy_repo_is_clean` is removed
- [ ] every audit sets `res.skipped` with a reason when it cannot run
- [ ] every `Finding` carries literal evidence — command output or a file
      excerpt, not a paraphrase
- [ ] no audit writes to the repository it is auditing

That last one has bitten this project: a benchmark invoked a CLI without an
output flag and silently overwrote the submission artifact three times per run.
"""


def new_plugin(name: str, detect: str, category: str, dest: Path,
               title: str = "") -> list[Path]:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    mod = slug.replace("-", "_")
    cls = "".join(part.capitalize() for part in re.split(r"[-_]", slug))
    title = title or f"{slug.replace('-', ' ').title()} audits"

    pkg = dest / mod
    pkg.mkdir(parents=True, exist_ok=True)
    fields = dict(name=slug, cls=cls, title=title, detect=detect,
                  category=category, module=mod,
                  parent=str(Path(detect).parent).replace("\\", "/"))

    written = []
    for path, body in (
        (pkg / "__init__.py", PLUGIN.format(**fields)),
        (pkg / f"test_{mod}_plugin.py", TEST.format(**fields)),
        (pkg / "README.md", README.format(**fields)),
    ):
        path.write_text(body, encoding="utf-8")
        written.append(path)
    return written
