"""Diagram generation.

Every diagram here is GENERATED from a data structure, never hand-drawn. A
hand-drawn architecture diagram is a claim about the code; a generated one is a
projection of it. When they disagree, only one of them is wrong in a way you
can fix.

Output is Mermaid, so it renders in GitHub, in most editors, and in an artifact
page, with no build step and no external service.

    orchestrate viz decisions > docs/decisions.mmd
    orchestrate viz --all docs/
"""

from __future__ import annotations

from ..memory.store import EngineeringMemory

HEADER = "%% generated by `orchestrate viz` -- do not hand-edit\n"

THEME = """
  classDef det fill:#132b3a,stroke:#3d7ea6,color:#e8f2f7;
  classDef model fill:#3a2a13,stroke:#a67c3d,color:#f7f0e8;
  classDef gate fill:#2b1330,stroke:#8f4fa6,color:#f4e8f7;
  classDef out fill:#17331f,stroke:#3f8f52,color:#e6f2e9;
  classDef rej fill:#3b1d1d,stroke:#b04141,color:#f2e6e6;
""".rstrip()


def architecture() -> str:
    """The reference router. Colour encodes TRUST, not layer: blue is
    deterministic, amber is model output, purple is a gate."""
    return HEADER + """graph TD
  IN[/"messages.csv + history + media"/]
  LOAD["loader<br/>tolerant decode, per-row isolation"]
  MEDIA{{"media backend<br/>(pluggable, default-local)"}}
  OCR["image OCR<br/>-> SAFETY TIER ONLY"]
  ASR["voice ASR<br/>-> full participation"]
  FEAT["feature extraction<br/>28 lexicons, 52 fields"]
  T1["TIER 1 · SAFETY"]
  T2["TIER 2 · RELATIONSHIP / URGENCY"]
  T3["TIER 3 · ENGAGEMENT"]
  DEF["DEFAULT"]
  ARB{{"LLM arbitration<br/>OPT-IN, default OFF"}}
  EV["evidence retrieval<br/>rule-scoped pool -> BM25"]
  OUT[/"output.csv (pinned hash)"/]

  IN --> LOAD --> MEDIA
  MEDIA --> OCR
  MEDIA --> ASR
  ASR --> FEAT
  OCR -. "safety signals only" .-> T1
  LOAD --> FEAT --> T1
  T1 -- "no match" --> T2 -- "no match" --> T3 -- "no match" --> DEF
  T1 --> EV
  T2 --> EV
  T3 --> EV
  DEF --> EV
  EV --> ARB --> OUT

  class LOAD,FEAT,T1,T2,T3,DEF,EV det;
  class OCR,ASR model;
  class MEDIA,ARB gate;
  class OUT,IN out;
""" + THEME


def trust_boundaries() -> str:
    """The asymmetry that made enabling OCR a zero-regression change."""
    return HEADER + """graph LR
  subgraph AUTHORED_BY_SENDER["authored by the sender"]
    TEXT["message_text"]
    VOICE["voice transcript<br/>(IS the message)"]
  end
  subgraph AUTHORED_BY_OTHERS["authored by a third party"]
    IMG["text inside an image"]
    FWD["forwarded payload"]
  end
  INTENT["INTENT<br/>what the sender meant"]
  SAFETY["SAFETY<br/>is this dangerous"]

  TEXT --> INTENT
  TEXT --> SAFETY
  VOICE --> INTENT
  VOICE --> SAFETY
  IMG --> SAFETY
  FWD --> SAFETY
  IMG -. "BLOCKED" .-x INTENT
  FWD -. "BLOCKED" .-x INTENT

  class TEXT,VOICE det;
  class IMG,FWD model;
  class INTENT,SAFETY out;
""" + THEME + """
  linkStyle 6,7 stroke:#b04141,stroke-width:2px;"""


def evaluation_pipeline() -> str:
    """How a proposed change becomes a shipped change. The loop back to
    'reject and record' is the part most processes omit."""
    return HEADER + """flowchart TD
  P(["proposal"]) --> M{"prior art<br/>in memory?"}
  M -- "rejected before" --> RC{"reconsideration<br/>condition met?"}
  RC -- no --> STOP["STOP<br/>blocked by prior art"]
  RC -- yes --> C
  M -- no --> C{"ceiling analysis<br/>rows this could fix"}
  C -- "0" --> STOP2["STOP<br/>no headroom"]
  C -- ">0" --> B["build the STRONGEST<br/>version of the idea"]
  B --> NEG{"negative control:<br/>break it on purpose --<br/>does the harness notice?"}
  NEG -- no --> FIX["the harness is broken.<br/>fix that first"]
  FIX --> NEG
  NEG -- yes --> MEAS["measure in the<br/>SHIPPED configuration"]
  MEAS --> D{"better on the<br/>metric you are graded on?"}
  D -- yes --> SHIP["ship + re-pin hash<br/>+ log cause/effect"]
  D -- no --> REJ["REJECT<br/>record the number<br/>+ reconsideration condition"]
  REJ --> KB[("Engineering Memory")]
  SHIP --> KB
  STOP --> KB
  STOP2 --> KB

  class STOP,STOP2,REJ,FIX rej;
  class SHIP,KB out;
  class NEG,MEAS,D,C,M,RC gate;
""" + THEME


def rule_engine() -> str:
    return HEADER + """flowchart TD
  START(["features extracted"]) --> S{"TIER 1 · SAFETY<br/>13 rules"}
  S -- match --> SO["mute / scam · notify / urgent<br/>first match wins"]
  S -- "no match" --> R{"TIER 2 · RELATIONSHIP / URGENCY<br/>14 rules"}
  R -- match --> RO["notify · digest"]
  R -- "no match" --> E{"TIER 3 · ENGAGEMENT<br/>13 rules"}
  E -- match --> EO["digest · mute"]
  E -- "no match" --> D["DEFAULT<br/>1 rule"]
  SO --> INV
  RO --> INV
  EO --> INV
  D --> INV
  INV["INVARIANTS<br/>· first match wins within a tier<br/>· 0 unreachable rules (proven, not sampled)<br/>· 0 shadowed rules<br/>· every output attributable to a named rule"]

  class S,R,E,D det;
  class INV out;
""" + THEME


def audit_pipeline() -> str:
    return HEADER + """flowchart LR
  REPO[/"repository"/] --> DET{"plugin detect<br/>(by SHAPE, never by name)"}
  DET --> G["generic audits<br/>git · secrets · fresh clone<br/>determinism · staleness · docs"]
  DET --> D["domain audits<br/>spec · leakage · evidence<br/>output sanity"]
  G --> AGG
  D --> AGG
  AGG["aggregate"] --> BL{"any BLOCKER?"}
  BL -- yes --> NS["DO NOT SHIP<br/>score capped at 49"]
  BL -- no --> SC["score = mean of<br/>category scores"]
  NS --> REP
  SC --> REP
  REP["report:<br/>BLOCKERS PRINTED ABOVE THE SCORE"]
  MEM[("Engineering Memory")] -. "attaches prior art<br/>to each finding" .-> AGG

  class NS rej;
  class REP,MEM out;
  class DET,BL gate;
""" + THEME


def regression_flow() -> str:
    return HEADER + """flowchart TD
  C["a change"] --> H{"pinned output hash<br/>still matches?"}
  H -- yes --> Z["0 rows changed.<br/>state that -- it is a RESULT,<br/>not a non-event"]
  H -- no --> DIFF["diff the rows"]
  DIFF --> EACH["for EACH changed row:<br/>why is the new value correct?"]
  EACH --> J{"can you name<br/>the reason?"}
  J -- no --> REV["revert. an unexplained<br/>row change is a regression<br/>you have not found yet"]
  J -- yes --> RP["re-pin + append to the RE-PIN LOG:<br/>cause · effect · score delta"]
  Z --> DOC["document the zero.<br/>'OCR changed 0 of 110 rows'<br/>is a defensible sentence"]

  class REV rej;
  class RP,DOC,Z out;
  class H,J gate;
""" + THEME


def submission_pipeline() -> str:
    return HEADER + """flowchart TD
  A["1 · freeze code"] --> B["2 · clear ALL credentials<br/>run in the SHIPPED configuration"]
  B --> C["3 · regenerate the artifact<br/>from a fresh clone"]
  C --> D["4 · hash every deliverable<br/>record the hashes"]
  D --> E{"5 · does the fresh-clone<br/>artifact match the<br/>committed one?"}
  E -- no --> F["STALE. the committed artifact<br/>was not produced by the<br/>committed code"]
  F --> C
  E -- yes --> G["6 · run the full evaluator<br/>expect 0 blockers"]
  G --> H["7 · negative control:<br/>inject defects, confirm<br/>the evaluator fails"]
  H --> I["8 · read the log/transcript<br/>for leaked secrets"]
  I --> J["9 · attest authorship YOURSELF"]
  J --> K["SUBMIT"]

  class F rej;
  class K,H out;
  class E gate;
""" + THEME


DIAGRAMS = {
    "architecture": ("System architecture (trust-coloured)", architecture),
    "trust": ("Modality trust boundaries", trust_boundaries),
    "evaluation": ("Proposal -> ship or reject", evaluation_pipeline),
    "rules": ("Rule engine tiers and invariants", rule_engine),
    "audit": ("Audit pipeline", audit_pipeline),
    "regression": ("Regression / re-pin flow", regression_flow),
    "submission": ("Release and submission pipeline", submission_pipeline),
}


def decisions(memory: EngineeringMemory, focus: str = "") -> str:
    return HEADER + memory.mermaid(focus)


def timeline(memory: EngineeringMemory) -> str:
    return HEADER + memory.timeline()
